# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLgjVOk_CKN7AQ92ass3-aT7oqlbUm0O
"""

import pygame
import random
import math

# --- CONFIGURATION ---
WIDTH, HEIGHT = 1000, 700
BG_COLOR = (0, 0, 0)
NOISE_COLOR = (200, 200, 200) # Static Grey/White
TEXT_COLOR = (255, 195, 0) # Deep Gold
FONT_SIZE = 40

class Particle:
    def __init__(self):
        self.reset()

    def reset(self):
        self.x = random.randint(0, WIDTH)
        self.y = random.randint(0, HEIGHT)
        self.size = random.randint(1, 3)
        self.speed = random.randint(5, 15) # High speed = High Entropy

    def update(self, entropy_level):
        # High Entropy = Chaotic movement
        if entropy_level > 0.1:
            self.x += random.randint(-self.speed, self.speed) * entropy_level
            self.y += random.randint(-self.speed, self.speed) * entropy_level

        # Low Entropy = Move toward edges (Clearing effect)
        else:
            dx = self.x - WIDTH/2
            dy = self.y - HEIGHT/2
            dist = math.sqrt(dx*dx + dy*dy)
            if dist > 0:
                self.x += (dx/dist) * 20 # Explode outward
                self.y += (dy/dist) * 20

        # Keep inside bounds only if high entropy
        if entropy_level > 0.5:
            if self.x < 0: self.x = WIDTH
            if self.x > WIDTH: self.x = 0
            if self.y < 0: self.y = HEIGHT
            if self.y > HEIGHT: self.y = 0

    def draw(self, surface):
        pygame.draw.circle(surface, NOISE_COLOR, (int(self.x), int(self.y)), self.size)

# --- SETUP ---
pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Day 2: The Entropy Shield")
font = pygame.font.SysFont("monospace", FONT_SIZE)
clock = pygame.time.Clock()

particles = [Particle() for _ in range(2000)] # 2000 particles of noise
user_text = ""
entropy = 1.0 # Starts at 100% Chaos

running = True
while running:
    screen.fill(BG_COLOR)

    # 1. UPDATE PARTICLES BASED ON ENTROPY
    for p in particles:
        p.update(entropy)
        p.draw(screen)

    # 2. DRAW THE INTENT TEXT (Glowing Gold)
    text_surface = font.render(user_text + "|", True, TEXT_COLOR)
    rect = text_surface.get_rect(center=(WIDTH/2, HEIGHT/2))

    # Add a black box behind text so it's readable over noise
    pygame.draw.rect(screen, BG_COLOR, rect.inflate(20, 10))
    screen.blit(text_surface, rect)

    pygame.display.flip()
    clock.tick(60)

    # 3. EVENT HANDLING
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_RETURN:
                entropy = 0.0 # Clear screen on Enter
            elif event.key == pygame.K_BACKSPACE:
                user_text = user_text[:-1]
                entropy = min(1.0, entropy + 0.05) # Backspace increases chaos
            else:
                user_text += event.unicode
                # Typing reduces entropy
                entropy = max(0.2, entropy - 0.05)

pygame.quit()